# KitPvP Config

kill-rewards:
  message: 'ยง6You have recieved ยงa%m ยง6for killing ยง4%p'
  reward-amount: 5.0
  potion-effects:
   - blindness
   - poison
   - hunger
   - weakness
   - slow
   - wither
   - confusion
launch:
  launchpad-material: STONE_PLATE
  velocity-multiplier: 6
  launch-check-tick-interval: 0
